version: '3.7'
services:
  # booquet:
  #   image: booquet/app
  #   build:
  #     context: ./packages/core
  #     args:
  #       - PRISMA_DB_URL=${PRISMA_DB_URL}
  #   ports:
  #     - 4000:4000
  #   env_file:
  #     - ./.env
  #   environment:
  #     # Override REDIS_HOST in local development to point at internal docker network.
  #     - REDIS_HOST=gql-subscriptions
  #   depends_on:
  #     - redis
  redis:
    image: redis:6-alpine
    container_name: gql-subscriptions
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: booquet
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: booquet-db
  redis:
    name: booquet-cache
