FROM node:14-alpine as build

# Install necessary tools for bcrypt to run in docker before dependency install.
RUN apk add --virtual builds-deps build-base python curl bash

# Node-prune to remove any unnecessary files
RUN curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b /usr/local/bin
