version: '3.7'
services:
    postgres:
        image: postgres:12
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${PRISMA_USERNAME}
            POSTGRES_PASSWORD: ${PRISMA_PASSWORD}
            POSTGRES_DB: ${PRISMA_DB_NAME}
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:
        name: nest-db
