version: '3.7'
services:
  booquet:
    image: booquet/app
    build:
      context: .
      dockerfile: ./packages/core/Dockerfile
      args:
        - PRISMA_DB_URL=${PRISMA_DB_URL}
    ports:
      - 4000:4000
    environment:
      # A mix of fake and real data, depending on the variable.
      - FE_URL=docs.nestjs.com
      - BE_URL=docs.nestjs.com
      - PRISMA_DB_URL=${PRISMA_DB_URL}
      - JWT_SECRET=hello-world
      - REFRESH_SECRET=hello-world
      - POSTMARK_KEY=hello-world
      - EMAIL_FROM_ADDRESS=test@test.com
      - CONTENTFUL_SPACE=hello-world
      - CONTENTFUL_ENVIRONMENT=staging
      - CONTENTFUL_MANAGEMENT_TOKEN=hello-world
      - CONTENTFUL_ACCESS_TOKEN=hello-world
      - CONTENTFUL_WEBHOOK_SECRET=hello-world
      - STRIPE_API_KEY=hello-world
      - STRIPE_WEBHOOK_SECRET=hello-world
      - REDIS_HOST=gql-subscriptions
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:6-alpine
    container_name: gql-subscriptions
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "booquet"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: booquet-db
  redis:
    name: booquet-cache
