version: '3.7'
services:
  redis:
    image: redis:6-alpine
    container_name: gql-subscriptions
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PRISMA_USERNAME}
      POSTGRES_PASSWORD: ${PRISMA_PASSWORD}
      POSTGRES_DB: ${PRISMA_DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: booquet-db
  redis:
    name: booquet-cache
